---
- name: Install DVWA Application
  become: yes
  hosts: all

  tasks:
    - name: Install prerequisites
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - php-fpm
        - mysql-server
        - php-mysql
        - php-gd
        - php-curl
        - php-json
        - php-mbstring
        - php-xml
    - name: Clone repositories
      git:
        repo: https://github.com/ethicalhack3r/DVWA.git
        dest: /usr/share/nginx/html