---
- name: Install DVWA Application
  become: yes
  hosts: all
  vars:
    repo: 'https://github.com/ethicalhack3r/DVWA.git'
  tasks:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php-fpm
        - mysql-server
        - php-mysql
        - php-gd
        - php-curl
        - php-json
        - php-mbstring
        - php-xml
    - name: Clone repository
      git:
        repo: "{{ repo }}"
        dest: "{{ '/usr/share/nginx/html/' ~ repo_name }}"
      vars:
        repo_name: "{{ repo.rsplit('/', 1)[-1].split('.', 1)[0] }}"
