---
- name: NGINX configuration
  become: yes
  hosts: all
  vars:
    server_name: 18.212.232.187
    root_directory: '/usr/share/nginx/html/DVWA'
    index_file: index.php
  tasks:
    - name: Template nginx file
      template:
        src: /home/ubuntu/Desktop/app_protect/nginx.conf.j2
        dest: /etc/nginx/conf.d/dvwa.conf
        mode: '0644'
    - name: Changing permission /var/run/php/php7.4-fpm.sock
      file:
        dest: /var/run/php/php7.4-fpm.sock
        mode: '0667'
