---
- name: NGINX configuration
  become: yes
  hosts: all
  vars:
    server_name: 34.234.79.160
    root_directory: '/usr/share/nginx/html/DVWA'
    index_file: index.php
  tasks:
    - name: Template nginx file
      template:
        src: /home/ubuntu/Desktop/app_protect/nginx.conf.j2
        dest: /etc/nginx/conf.d/dvwa.conf
        mode: '0644'
    - name: Reload service
      systemd:
        state: restarted
        name: nginx
    - name: Changing permission /var/run/php/php7.4-fpm.sock
      file:
        dest: /var/run/php/php7.4-fpm.sock
        mode: '0667'
